env: dev
server:
  port: 8100
order:
  server:
    port: ${server.port}
eureka:
  instance:
    hostname: localhost
    virtual-host-name: order-service
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7071/eureka
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: linbao
    password: 123456