env: test
spring:
  application:
    name: order-service
  profiles:
    active: ${env}
server:
  port: 8100
eureka:
  instance:
    hostname: localhost
    virtual-host-name: order-service
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7071/eureka
  datasource:
    url: mysql://localhost:3306/order
    username: linbao
    password: 123456