env: dev
server:
  port: 8000
cis:
  server:
    port: ${server.port}
eureka:
  instance:
    hostname: localhost
    virtual-host-name: user-service
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7071/eureka