env: test
server:
  port: 8000
cis:
  server:
    port: ${server.port}
eureka:
  instance:
    hostname: localhost
    virtual-host-name: user-service
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7071/eureka
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/customer
    username: linbao
    password: 123456